title: "Juego Piedra Papel Tijera"
description: "Juego tradicional implementado en Python con diagrama funcional y código."
theme: minima

# Opciones del tema
show_excerpts: true   # Muestra extractos en la página principal
author: "Tu Nombre"

# Configuración de Markdown
markdown: kramdown
highlighter: rouge

# Links en la cabecera
header_pages:
  - index.md

# Personalización
minima:
  skin: auto   # Usa claro u oscuro según la configuración del navegador
